### ISSUE TITLE
[Crash Report]: Needing me to install fabric when I already have it

### ISSUE THREAD

**Issue by Temperative** [Mrbysco/Durability-Notifier#11]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

Latest Fabric Version

### Mod version

1.3.1

### Java version

Java 8 Verson 351

### Issue Description

I have fabric downloaded and whenever I try to open minecraft with this mod, it's wanting me to download any version of fabric.

![image_2023-03-07_094858208](https://user-images.githubusercontent.com/127227298/223474281-d28688f5-c3cf-4e2d-a05f-ce639ab42bad.png)
![image_2023-03-07_094928477](https://user-images.githubusercontent.com/127227298/223474402-829dcfe4-f231-4f19-af18-0e198f98ee1a.png)

### Additional Information

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Durability Notifier' (durabilitynotifier) 1.3.1 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
	

Exit Code: 1

**Comment by Mrbysco** [comment]
Do you have the Fabric API installed? https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by Temperative** [comment]
> Do you have the Fabric API installed? https://www.curseforge.com/minecraft/mc-mods/fabric-api

Thank you very much. It works now!
