### ISSUE TITLE
[Bug]: Not functional on multiplayer servers even if mod is installed server side

### ISSUE THREAD

**Issue by NighthowlerStudios** [Mrbysco/Durability-Notifier#4]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.16.5-36.2.22

### Mod version

1.0.1-1.16.3

### Java version

Java 8 Update 51

### Issue Description

This mod does not work entirely when playing on a multiplayer server, even if the mod is installed server side.  It is possible your mod does not read properly from dedicated server type packets for item durability

**Comment by Mrbysco** [comment]
The mod works fine on servers, I've tested it against both vanilla and forge servers.
It tells you the durability the moment you try and use the tool NOT when it takes damage!

**Comment by NighthowlerStudios** [comment]
It was not functional for a moment due to autosave lag.  Sorry.
