### ISSUE TITLE
also check and warn about elytra?

### ISSUE THREAD

**Issue by dr-hagar** [Mrbysco/Durability-Notifier#7]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Thanks for a useful mod :)

It seems the mod is not warning when worn elytra reaches 10% durability,
it would be great if this feature was included.

**Comment by Mrbysco** [comment]
The mod currently only checks the item you're using (in your hand/off-hand) It doesn't check armor slots

**Comment by Mrbysco** [comment]
In version 1.2 there's a config option to allow it to check armor slots

**Comment by dr-hagar** [comment]
Thanks, just tested this, and it works perfectly :)

It would be cool to also see the actual durability value (so you can cut it closer,
the time when you have to swap out armour/elytra).

(but I can add that myself of course too)
