### ISSUE TITLE
[Bug]: Does not work while hitting an entity

### ISSUE THREAD

**Issue by Hlebuw3k** [Mrbysco/Durability-Notifier#8]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

Fabric

### Mod version

1.2

### Java version

17.0.2

### Issue Description

Im at my skeleton grinder, and hitting them with an iron sword, and the durability ping does not happen unless i hit (or right click) a block. This is on a Paper server with Fabric client, with minor visual (no gameplay) client side modifications.

### Additional Information

hitting a wall (ping, as expected):
![image](https://user-images.githubusercontent.com/78320892/163664954-ff5aa9d7-44b5-44a5-a098-b7b95417376e.png)
hitting the skeletons (no ping, unexpected): 
![image](https://user-images.githubusercontent.com/78320892/163664971-87daa353-4dde-49f3-b3f5-54b61fc471be.png)

**Comment by Mrbysco** [comment]
Fixed next version
