### ISSUE TITLE
[Bug]: Recognizes Unbreakable NBT tag as 0 durability

### ISSUE THREAD

**Issue by litoj** [Mrbysco/Durability-Notifier#9]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

fabric, latest 1.18.2

### Mod version

latest

### Java version

Java 18

### Issue Description

When I use an item that is Unbreakable:1b, I keep getting the notifier that my item is bellow 1% durability (I have this mod set to notify me at 1%) although the item is full durability, unused.

**Comment by Mrbysco** [comment]
A new version that should fix this issue has been released
